### ISSUE TITLE
Can u share the code to generate vocabulary ?

### ISSUE THREAD

**Issue by liesun1994** [wszlong/transformer#12]

**Comment by wszlong** [comment]
get_vocab.py:

#! /usr/bin/env python
##Usage: python get_vocab.py < trainset > vocab
import sys
from collections import Counter
c = Counter()

for line in sys.stdin:
    for word in line.split():
        c[word] += 1

for key,f in sorted(c.items(), key=lambda x: x[1], reverse=True):
    #print key, f ## generate token and num
    print key ## generate token

**Comment by liesun1994** [comment]
What's the index of the special symbols ? Such as "UNK", "EOS" or other symbols in [https://github.com/wszlong/sb-nmt](https://github.com/wszlong/sb-nmt)

**Comment by liesun1994** [comment]
THX

**Comment by wszlong** [comment]
<pad> and <EOS> have been inserted as reserved tokens in code (see util/text_read.py).
For sb-nmt, you need manually <l2r>,<r2l> and UNK at the beginning of vocab.

**Comment by wszlong** [comment]
PAD and EOS and have been inserted as reserved tokens in code (see util/text_read.py).
For sb-nmt, you need manually add L2R, R2L , and UNK at the beginning of vocab.

**Comment by Shajiu** [comment]
你好！我预处理生成词汇表之后，运行训练命令时出现如下错误这是怎么回事儿呢？
Use `tf.keras.layers.Conv2D` instead.
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    tf.app.run()
  File "/home2/sj/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home2/sj/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home2/sj/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run.py", line 96, in main
    train_steps=FLAGS.train_steps)
  File "/home2/sj/translation/transformer-master/utils/trainer_utils.py", line 136, in run
    model_fn_ops = model_fn(features, labels) #total_loss, train_op
  File "/home2/sj/translation/transformer-master/utils/trainer_utils.py", line 303, in model_fn
    result_list = get_model()
  File "/home2/sj/translation/transformer-master/utils/trainer_utils.py", line 284, in get_model
    sharded_logits, training_loss, extra_loss = model_class.model_fn(features)
  File "/home2/sj/translation/transformer-master/models/transformer.py", line 114, in model_fn
    body_outputs, sharded_features["targets"], self._data_parallelism))
  File "/home2/sj/translation/transformer-master/models/transformer.py", line 400, in top_sharded
    weights_fn=weights_fn)
  File "/home2/sj/translation/transformer-master/utils/parallel.py", line 166, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/home2/sj/translation/transformer-master/models/common_layers.py", line 284, in padded_cross_entropy
    with tf.name_scope("padded_cross_entropy", [logits, labels]):
  File "/home2/sj/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6450, in __init__
    "pass this into the `values` kwarg." % type(default_name))
TypeError: `default_name` type (<class 'list'>) is not a string type. You likely meant to pass this into the `values` kwarg.
